.TH "C:/Users/Nima/Documents/KL/main.cpp" 3 "Tue Dec 16 2025 05:05:30" "Kernighan Lin algorithm (KL)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Nima/Documents/KL/main.cpp \- Entry point for the KL partition program\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <QCoreApplication>\fP
.br
\fR#include <QDebug>\fP
.br
\fR#include <QFile>\fP
.br
\fR#include <QString>\fP
.br
\fR#include 'kl_partition\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Detailed Description"
.PP 
Entry point for the KL partition program\&. 

This program reads an adjacency matrix from a CSV file specified via command line or console input, performs KL partitioning with clustering, and writes results to output files:
.IP "\(bu" 2
partition\&.txt : node -> partition mapping
.IP "\(bu" 2
metrics\&.txt : cut and cluster variance metrics
.IP "\(bu" 2
trace\&.csv : cut evolution during KL swaps
.PP

.PP
Usage: 
.PP
.nf
\&./KL input\&.csv

.fi
.PP
 
.PP
Definition in file \fBmain\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.SH "Author"
.PP 
Generated automatically by Doxygen for Kernighan Lin algorithm (KL) from the source code\&.
