.TH "C:/Users/Nima/Documents/KL/README.md" 3 "Tue Dec 16 2025 05:05:30" "Kernighan Lin algorithm (KL)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Nima/Documents/KL/README.md
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Kernighan Lin algorithm (KL) from the source code\&.
